version: '3.9'

services:
  backend:
    build:
      context: ./VueTsAppWebApi/VueTsAppWebApi
    image: vuetsappwebapi:latest
    ports:
      - "8080:80"
      - "8081:443"
    environment:
        - ASPNETCORE_URLS=https://0.0.0.0:443;http://0.0.0.0:80
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pem
        - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/key.pem

  frontend:
    build:
      context: ./TsVueClientApp/tsvueclientapp
    image: tsvueclientapp:latest
    ports:
      - "8082:80"
      - "8083:443"
    environment:
      - API_BASE_URL=http://localhost:8080
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
