version: '3.8'

services:
  backend:
    build:
      context: ./VueTsAppWebApi/VueTsAppWebApi
    image: vuetsappwebapi:latest
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    restart: always

  frontend:
    build:
      context: ./TsVueClientApp/tsvueclientapp
    image: tsvueclientapp:latest
    expose:
      - "80"
    environment:
      - API_BASE_URL=https://localhost:8085/webapi/api
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8084:80"
      - "8085:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    restart: always
